### ISSUE TITLE
failed to find target android-21

### ISSUE THREAD

**Issue by jiqimaogou** [jacobtabak/Fragment-Switcher#1]
Error:Cause: failed to find target android-21 : C:\sdk
<a href="install.android.platform">Install missing platform(s) and sync project</a>

**Comment by jacobtabak** [comment]
Just fixed this - please let me know if it resolves your issue.

**Comment by jiqimaogou** [comment]
09-26 06:51:13.237: E/AndroidRuntime(4556): Process: me.tabak.fragmentswitcher.sample, PID: 4556
09-26 06:51:13.237: E/AndroidRuntime(4556): java.lang.NullPointerException
09-26 06:51:13.237: E/AndroidRuntime(4556):     at me.tabak.fragmentswitcher.FragmentSwitcher.populate(FragmentSwitcher.java:281)
09-26 06:51:13.237: E/AndroidRuntime(4556):     at me.tabak.fragmentswitcher.FragmentSwitcher.populate(FragmentSwitcher.java:230)
09-26 06:51:13.237: E/AndroidRuntime(4556):     at me.tabak.fragmentswitcher.FragmentSwitcher.onMeasure(FragmentSwitcher.java:299)

**Comment by jacobtabak** [comment]
Thanks - separate issue, I just added a null check for the PageChangedListener.  Appreciate the feedback

**Comment by jiqimaogou** [comment]
could you make your project at api < 20, because android L is not stable yet. we must download the newest development environment.

**Comment by jacobtabak** [comment]
API level 20 is 4.4W which is stable.  API 21 will be L.  Now, the project should be compatible with API 7 and up.
