### ISSUE TITLE
Hashmaps

### ISSUE THREAD

**Issue by PGMacDesign** [jacobtabak/Fragment-Switcher#5]
Hi there, Love the library, use it frequently. Quick  Q, what would I need to change make this functional with a HashMap<Integer, Fragment> as opposed to a collection (list/ Arraylist/ etc)? I already changed the code within the FragmentStateArrayPagerAdapter to mirror it, but I am unsure if I need to make changes also in just the FragmentSwitcher class or in multiple other ones too.

**Comment by jacobtabak** [comment]
Sorry I didn't see your issue earlier.  Just extend `FragmentPagerAdapter` or `FragmentStatePagerAdapter` (from the support lib, not from this library) and provide your own hashmap based implementation.

**Comment by PGMacDesign** [comment]
Excellent, thanks!
